package validate

type RuleID string

const (
	RuleOutputDirectoryNameInvalid       RuleID = "output.directory-name.invalid"
	RuleNetworkNameRequired              RuleID = "network.name.required"
	RuleNetworkNameInvalid               RuleID = "network.name.invalid"
	RuleOrganizationsRequired            RuleID = "organizations.required"
	RuleOrganizationNameRequired         RuleID = "organization.name.required"
	RuleOrganizationDomainRequired       RuleID = "organization.domain.required"
	RuleOrganizationDomainDuplicate      RuleID = "organization.domain.duplicate"
	RuleOrganizationUsersInvalid         RuleID = "organization.users.invalid"
	RuleDomainInvalid                    RuleID = "domain.invalid"
	RuleCertificateAuthorityPortInvalid  RuleID = "certificate-authority.port.invalid"
	RulePeerNameRequired                 RuleID = "peer.name.required"
	RulePeerSubdomainRequired            RuleID = "peer.subdomain.required"
	RulePeerPortInvalid                  RuleID = "peer.port.invalid"
	RulePeerInternalPortInvalid          RuleID = "peer.internal-port.invalid"
	RulePeerNameDuplicate                RuleID = "peer.name.duplicate"
	RulePeerSubdomainDuplicate           RuleID = "peer.subdomain.duplicate"
	RuleOrdererNameRequired              RuleID = "orderer.name.required"
	RuleOrdererSubdomainRequired         RuleID = "orderer.subdomain.required"
	RuleOrdererPortInvalid               RuleID = "orderer.port.invalid"
	RuleOrdererInternalPortInvalid       RuleID = "orderer.internal-port.invalid"
	RuleOrdererNameDuplicate             RuleID = "orderer.name.duplicate"
	RuleChaincodeNameRequired            RuleID = "chaincode.name.required"
	RuleChaincodePathRequired            RuleID = "chaincode.path.required"
	RuleChaincodeVersionRequired         RuleID = "chaincode.version.required"
	RuleChaincodeNameDuplicate           RuleID = "chaincode.name.duplicate"
	RuleProfileOrganizationsRequired     RuleID = "profile.organizations.required"
	RuleProfileNameRequired              RuleID = "profile.name.required"
	RuleProfileNameDuplicate             RuleID = "profile.name.duplicate"
	RuleChannelProfileRequired           RuleID = "channel.profile.required"
	RuleChannelNameRequired              RuleID = "channel.name.required"
	RuleChannelNameInvalid               RuleID = "channel.name.invalid"
	RuleChannelNameDuplicate             RuleID = "channel.name.duplicate"
	RuleChannelProfileUndefined          RuleID = "channel.profile.undefined"
	RuleChannelCapabilityUnsupported     RuleID = "capability.channel.unsupported"
	RuleApplicationCapabilityUnsupported RuleID = "capability.application.unsupported"
	RuleOrdererCapabilityUnsupported     RuleID = "capability.orderer.unsupported"
	RuleOrganizationNameDuplicate        RuleID = "organization.name.duplicate"
	RulePeerVersionInvalid               RuleID = "peer.version.invalid"
	RuleOrdererVersionInvalid            RuleID = "orderer.version.invalid"
	RuleOrdererTopologyRequired          RuleID = "orderer.topology.required"
	RuleBootstrapOrganizationsMultiple   RuleID = "organization.bootstrap.multiple"
	RuleConsensusTypeInvalid             RuleID = "profile.consensus-type.invalid"
	RuleProfileOrganizationUndefined     RuleID = "profile.organization.undefined"
	RuleExposedPortConflict              RuleID = "exposed-port.conflict"
)
