services:
  hfndm_database:
    container_name: hfndm_database
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - hfndm_database_volume:/var/lib/postgresql/data
    env_file:
      - ./env/.env.database
    networks:
      - hfndm_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "hfndmdb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  hfndm_api:
    container_name: hfndm_api
    build:
        context: ./../../
        dockerfile: ./.docker/api/Dockerfile
    env_file:
      - ./env/.env.api
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - hfndm_network
    restart: unless-stopped
    depends_on:
        hfndm_database:
            condition: service_healthy

volumes:
  hfndm_database_volume:
    name: hfndm_database_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres/data

networks:
  hfndm_network:
    name: hfndm_network